/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserProgress = IDL.Record({
  'finalSectionViewed' : IDL.Bool,
  'surpriseButtonsCompleted' : IDL.Bool,
  'teasingSectionCompleted' : IDL.Bool,
  'hasStarted' : IDL.Bool,
  'loveLetterCompleted' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'getAllUserProgress' : IDL.Func([], [IDL.Vec(UserProgress)], ['query']),
  'getFinalMessages' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getLoveLetterMessages' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getTeasingMessages' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProgress' : IDL.Func([IDL.Nat], [IDL.Opt(UserProgress)], ['query']),
  'initializeUserProgress' : IDL.Func([], [IDL.Nat], []),
  'updateUserProgress' : IDL.Func(
      [IDL.Nat, IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserProgress = IDL.Record({
    'finalSectionViewed' : IDL.Bool,
    'surpriseButtonsCompleted' : IDL.Bool,
    'teasingSectionCompleted' : IDL.Bool,
    'hasStarted' : IDL.Bool,
    'loveLetterCompleted' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'getAllUserProgress' : IDL.Func([], [IDL.Vec(UserProgress)], ['query']),
    'getFinalMessages' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getLoveLetterMessages' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getTeasingMessages' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProgress' : IDL.Func([IDL.Nat], [IDL.Opt(UserProgress)], ['query']),
    'initializeUserProgress' : IDL.Func([], [IDL.Nat], []),
    'updateUserProgress' : IDL.Func(
        [IDL.Nat, IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };